### ISSUE TITLE
iTerm2 interpret the colors as Generic RGB instead of Device RGB

### ISSUE THREAD

**Issue by jeanlauliac** [chriskempson/base16-iterm2#10]
Because of that, they appear lighter than in, say, Sublime Text. Is there any known way to fix this problem?

**Comment by joshdick** [comment]
Updating to the [iTerm2 v3 beta](https://iterm2.com/version3.html)) fixed this for me; colors display correctly.

This is possibly related to gnachman/iTerm2#149.

**Comment by jeanlauliac** [comment]
Ah you're right, I'll try. Meanwhile I had replaced the colors manually, as it was a one-time thing.
