### ISSUE TITLE
Sometimes crashes iTerm2 build 2.9.20150830 (beta)

### ISSUE THREAD

**Issue by exchgr** [chriskempson/base16-iterm2#11]
Sometimes, running one of these scripts crashes iTerm2 2.9 beta, whether from `.bashrc` or in the middle of a session.

**Comment by aaron-williamson** [comment]
I'm not sure why you would be running these as a script, these are configuration files for iTerm2 that should be imported as color schemes, not executed from the command line or a configuration file like `.bashrc`.
See installation instructions [here](http://iterm2colorschemes.com/) for how to use these files.

**Comment by exchgr** [comment]
Apologies, I think I meant to post this issue in the base16-shell repo. In any case, I can't remember the last time iTerm crashed for any reason, and it's on 3.0.10 now, so I'll close this.
