### ISSUE TITLE
iTerm/Shell colors look faded compared to vim colors

### ISSUE THREAD

**Issue by andrewkboyd** [chriskempson/base16-iterm2#14]
I am not certain where the issue is coming in, but my vim colors are much more rich than the terminal colors.  The screenshots show one tmux window with vim open showing the colors, and the other shows the shell with colors that look more faded.  

Any help is appreciated.

I am using iTerm2, terminal Vim, & base16-google.dark.256

`set background=dark`
`colorscheme base16-google`

![screen shot 2016-05-18 at 9 27 49 am](https://cloud.githubusercontent.com/assets/15125542/15360501/c8c14f28-1cdb-11e6-9f6c-f0fb3e3867ec.png)
![screen shot 2016-05-18 at 9 34 34 am](https://cloud.githubusercontent.com/assets/15125542/15360506/cd7bd740-1cdb-11e6-8b16-24e0e9467e82.png)

**Comment by aaron-williamson** [comment]
I may be wrong, but this looks to me like a lack of true color support from your terminal, with `termguicolors` enabled in vim. I experienced a similar issue myself specifically within iTerm2 + tmux, as tmux needs additional configuration to support true color.
The terminal without vim is showing the correct color, where as vim is only showing its closest available representation. I was able to fix this by adding the line `set-option -ga terminal-overrides ",xterm-256color:Tc"` to my `.tmux.conf` file.
So with that line, and `termguicolors` enabled in vim, using the base16-google.dark.256 theme, and base16_google airline theme I get this:
![image](https://cloud.githubusercontent.com/assets/9038848/20125850/9fecc672-a5ed-11e6-920c-7421146d3731.png)

Any additional styling to tmux there is from the rest of my tmux config, but the terminal and vim match properly.

**Comment by andrewkboyd** [comment]
So I'm not exactly sure what changed, but I re-imported google dark-base16 and tried playing around with a few settings. I'm not exactly sure which one fixed it, but everything is working well now. 

Thanks for the response, it spurred me to look into it again!

I will play around with the settings and see if I can figure out exactly what caused the change.
