### ISSUE TITLE
base16-tomorrow.light and base16-tomorrow.dark have changed.

### ISSUE THREAD

**Issue by swimyoung** [chriskempson/base16-iterm2#21]
Hi, first thank you for great project.

I found an issue while i use tomorrow theme

It was base16-tomorrow.dark color when i use base16-tomorrow.light theme in base16-iterm2
I think `base16-tomorrow.light` and `base16-tomorrow.dark` have changed.

**Comment by yiliangt5** [comment]
I found this issue as well.

**Comment by gmarmstrong** [comment]
I'm getting the same issue. They appear to be named incorrectly. Fixing this right now.

**Comment by CupricWolf** [comment]
I believe this isn't fully fixed. For example, using tomorrow dark my terminal looks like it has a light theme applied but then text that is "ansi-black" is actually black and using tomorrow light the terminal looks like it has a dark theme applied but "ansi-black" is actually white.

**Comment by chriskempson** [comment]
This repo is deprecated, please see: https://github.com/martinlindhe/base16-iterm2
